### PR TITLE
Clean up boilerplate and reorganise subdirectories

### PR DESCRIPTION
**Pull request by Alhadis**
Alright, brief summary:

* Atom's package manager (`apm`) expects users to publish their packages in a very, very specific and controlled way, meaning that any unconventional folder structures, mismatching metadata in `package.json`, and even your choice of version-string formatting – can all impact your ability to publish your work in stupid, illogical and utterly confusing ways.

* I've populated missing metadata using the keywords and repo description you added here on GitHub.

* I've remove myself from the readme's "Authors" section. While I'm humbled that you felt my help was worthy of credit, my creative input has been precisely squat. Pretty much all I did was take your work, swap some lines around, shove some double-quotes into that bitch, and manually convert your YAML file into a CSON file (CSON is like JSON, except nicer to read and write. Kinda).

* I deleted the specs that Atom's package generator created for you, as they're actually boilerplate tests for a completely different sort of package. Those were tests for a UI/component-type package, whereas syntax-highlighting packages are simpler and don't even have any executable source code half the time.

### CODE REVIEW

**Comment by Alhadis** [comment]
Now. Publication.

I assume you've:
1. Connected your GitHub account with [Atom.io](https://atom.io/account)
2. Have a GPG key setup with Git for signing release tags (you'll need it for `git tag -s` below)
3. Have `apm` available in your`$PATH` (just run `apm --version` to confirm. You should see some distracting colours and blobs of version info).

If the above criteria have been met, go ahead and run the following commands:

~~~shell
sed -i -e 's/\("version": "0\.\)0/\11/' package.json
rm package.json.bak
git add -u
git commit -m 'Release v0.1.0'
git tag -m v0.1.0 -s v0.1.0
git push origin master --tags
apm publish --tag v0.1.0
~~~

**Comment by Alhadis** [comment]
Oh! Forgot to mention, too: this wasn't so much about Atom as it was Linguist. 😉 Sublime Syntax isn't supported by GitHub's highlighting engine (which is based upon an [editor called TextMate](http://manual.macromates.com/en/language_grammars#naming_conventions)). Atom grammars are, however. And they're also the grammar format I'm best equipped to help with, so choosing it was a no-brainer. 😀

Because Linguist expects to find grammars in a top-level project directory named `grammars/`, it's especially important that Atom package conventions are used. =)

**Comment by Alhadis** [comment]
@joergen7 You'll, uh, need to merge this because I can't do it for you. 😛

**Comment by joergen7** [comment]
Sorry, I'm still figuring PRs out. I'm reviewing your changes right now.

**Comment by Alhadis** [comment]
You should see a green button called "Squash and merge" or something to do with merging.

screenshot-2018-8-30 github linguist

Push that motherfucker. =)

**Comment by joergen7** [comment]
Will do. I'm just taking these 10 min to make sure I understand where we're at.

**Comment by joergen7** [comment]
Now all that's left is adding this to apm. Also I guess, I'll put the sublime stuff somewhere else.

**Comment by joergen7** [comment]
@Alhadis Yay, I was able to publish the apm package. Now I have an apm package.

**Pull request merged**
